import partModel from './base/Model'
import partView from './base/View'
import partController from './base/Controller'
import partSwiper from './init-swiper'
import partSlide from './auto-slide-up'
import partTopbar from './sticky-topbar'
import partNav from './smoothly-navigation'
import partMessage from './message'
import '../css/loading.scss'
import '../css/main.scss'